'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
const GameAnalysis = dynamic(() => import('@/features/analysis/game-analysis').then(module => module.GameAnalysis), { ssr: false });
import { useRouter } from 'next/navigation';
import { ArrowLeftRight, ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight, Cpu, Users, Globe2, Flag, RotateCcw, ArrowUpRight, Copy, Check, Share2, Bookmark, Play, LoaderCircle, Volume2, VolumeX, Menu } from 'lucide-react';
import { GameDialog } from '@/components/game-dialog';
import { Board } from '@/features/board/board';
import { useGameAudio } from '@/features/game/use-game-audio';
import { api, useApp } from '@/components/providers';
import { afterLegalMove, newGame, play, replay, legalMoves, describeMove, inCheck, opposite, moveUci, type GameState, type Color, type Move } from '@/domain/xiangqi/rules';
import type { Command, OnlineGame } from '@/domain/contracts';
type Mode='cpu'|'local'|'online';
const reasonLabel:Record<string,string>={checkmate:'Checkmate',stalemate:'Stalemate — no legal moves','perpetual-check':'Perpetual check','repetition-review':'Repetition · review required','no-progress-review':'No progress · review required',timeout:'Time expired',resignation:'Resigned',agreement:'Draw agreed',cancelled:'Challenge cancelled',expired:'Invitation expired'};
function practiceSaveId(userId:string,sessionId:string){const key=`figure-practice:${userId}:${sessionId}`;let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id);}return id;}
function clock(ms:number){const seconds=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
export function GameRoom({gameId}:{gameId?:string}) {
 const router=useRouter(),{user,online,loading}=useApp();
 const {muted,playSound,toggleMuted}=useGameAudio();
 const [state,setState]=useState<GameState>(()=>newGame()),[mode,setMode]=useState<Mode>(gameId?'online':'cpu'),[remote,setRemote]=useState<OnlineGame|null>(null);
 const [selected,setSelected]=useState<number|null>(null),[human,setHuman]=useState<Color>('red'),[level,setLevel]=useState(2),[flipped,setFlipped]=useState(false),[labels,setLabels]=useState(false);
 const [panel,setPanel]=useState<'computer'|'friend'|'match'>('computer'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[thinking,setThinking]=useState(false),[queued,setQueued]=useState(false),[queueSince,setQueueSince]=useState<number|null>(null);
 const [cursor,setCursor]=useState<number|null>(null),[resigned,setResigned]=useState<Color|null>(null),[tick,setTick]=useState(0),[serverOffset,setServerOffset]=useState(0),[connected,setConnected]=useState(true),[copied,setCopied]=useState(false),[hydrated,setHydrated]=useState(false),[confirmReset,setConfirmReset]=useState(false),[savedVersion,setSavedVersion]=useState(-1);
 const [suggestion,setSuggestion]=useState<Move|null>(null);
 const [resultDismissed,setResultDismissed]=useState(false);
 const [menuOpen,setMenuOpen]=useState(Boolean(gameId));
 const [analysisMoves,setAnalysisMoves]=useState<Move[]|null>(null),[inviteUrl,setInviteUrl]=useState('');
 const sessionId=useRef(''),boardState=useRef(state),worker=useRef<Worker|null>(null),lastVersion=useRef(-1),pollRunning=useRef(false),errorRef=useRef(error),soundState=useRef({moveCount:0,ended:false}),remoteStatus=useRef<string|null>(null);
 useEffect(()=>{errorRef.current=error;},[error]);
 useEffect(()=>{boardState.current=state;},[state]);
 const receive=useCallback((game:OnlineGame)=>{if(game.version<lastVersion.current)return;const initialRemote=lastVersion.current===-1,hasNewMove=game.state.moves.length>boardState.current.moves.length;lastVersion.current=game.version;if(initialRemote)soundState.current.moveCount=game.state.moves.length;if(hasNewMove){setCursor(null);setSelected(null);}setRemote(game);setState(game.state);setServerOffset(game.serverNow-Date.now());setConnected(true);if(!initialRemote&&game.rematch_id)router.push(`/game/${game.rematch_id}`);},[router]);
 useEffect(()=>{sessionId.current=crypto.randomUUID();setLabels(localStorage.getItem('figure-labels')==='true');if(!gameId){try{const saved=JSON.parse(localStorage.getItem('figure-current')||'null');if(saved&&Array.isArray(saved.moves)&&saved.moves.length<=1000&&['cpu','local'].includes(saved.mode)){const restored=replay(saved.moves);soundState.current.moveCount=restored.moves.length;setState(restored);setMode(saved.mode);setHuman(saved.human==='black'?'black':'red');setFlipped(saved.human==='black');setResigned(saved.resigned==='red'||saved.resigned==='black'?saved.resigned:null);sessionId.current=typeof saved.id==='string'?saved.id:crypto.randomUUID();}}catch{localStorage.removeItem('figure-current');}}setHydrated(true);},[gameId]);
 useEffect(()=>{if(hydrated&&!gameId)localStorage.setItem('figure-current',JSON.stringify({id:sessionId.current,moves:state.moves,mode,human,resigned}));},[state,mode,human,resigned,hydrated,gameId]);
 useEffect(()=>{setTick(Date.now());const timer=setInterval(()=>setTick(Date.now()),500);return()=>clearInterval(timer);},[]);
 const refreshRemote=useCallback(async()=>{if(!gameId||!user||pollRunning.current)return;pollRunning.current=true;try{receive(await api<OnlineGame>(`games/${gameId}`));}catch(e){setConnected(false);void e;}finally{pollRunning.current=false;}},[gameId,user,receive]);
 const remoteReady=Boolean(remote);
 useEffect(()=>{if(gameId)setInviteUrl(`${location.origin}/game/${gameId}`);},[gameId]);
 useEffect(()=>{if(!gameId||!user||!remoteReady)return;void refreshRemote();const timer=setInterval(()=>{if(!document.hidden)void refreshRemote();},1500);const wake=()=>{if(!document.hidden)void refreshRemote();else setConnected(false);};const offline=()=>setConnected(false);document.addEventListener('visibilitychange',wake);window.addEventListener('online',wake);window.addEventListener('offline',offline);window.addEventListener('focus',wake);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',wake);window.removeEventListener('online',wake);window.removeEventListener('offline',offline);window.removeEventListener('focus',wake);};},[gameId,user,refreshRemote,remoteReady]);
 useEffect(()=>{if(!gameId||remote||!user)return;let cancelled=false;void api<OnlineGame>(`games/${gameId}/join`,{}).then(game=>{if(!cancelled){receive(game);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[gameId,remote,user,receive]);
 useEffect(()=>{if(!queued)return;const beat=async()=>{try{const result=await api<{gameId:string|null;queued:boolean;since:number|null}>('queue',{});if(result.gameId){setQueued(false);router.push(`/game/${result.gameId}`);}else setQueueSince(result.since);}catch(e){setError(e instanceof Error?e.message:'Could not match.');setQueued(false);}};void beat();const timer=setInterval(()=>{if(!document.hidden)void beat();},8000);return()=>clearInterval(timer);},[queued,router]);
 useEffect(()=>{const onKeyDown=(event:globalThis.KeyboardEvent)=>{if(menuOpen||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey)return;const target=event.target;if(target instanceof Element&&target.closest('input, textarea, select, [contenteditable="true"]'))return;if(event.key==='ArrowLeft'&&state.moves.length){event.preventDefault();setSuggestion(null);setCursor(current=>Math.max(0,(current??state.moves.length)-1));setSelected(null);}else if(event.key==='ArrowRight'&&cursor!==null){event.preventDefault();setCursor(current=>{if(current===null)return null;const next=current+1;return next>=state.moves.length?null:next;});setSelected(null);}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[cursor,state.moves.length,menuOpen,analysisMoves]);
 const gameEnded=Boolean(state.outcome||resigned||(remote&&['finished','review','aborted'].includes(remote.status)));
 useEffect(()=>{if(gameEnded)setMenuOpen(false);},[gameEnded]);
 useEffect(()=>{if(!hydrated)return;const previous=soundState.current;if(gameEnded&&!previous.ended)playSound('end');else if(state.moves.length>previous.moveCount){const move=state.moves.at(-1);if(move){const before=replay(state.moves.slice(0,-1));playSound(inCheck(state.position)?'check':before.position.board[move.to]?'capture':'move');}}previous.moveCount=state.moves.length;previous.ended=gameEnded;},[gameEnded,hydrated,playSound,state]);
 useEffect(()=>{const status=remote?.status??null;if(status==='active'&&remoteStatus.current==='waiting')playSound('start');remoteStatus.current=status;},[playSound,remote?.status]);
 useEffect(()=>{if(remote?.status==='active')setMenuOpen(false);},[remote?.status]);
 const myColor:Color=remote?(remote.red_id===user?.id?'red':'black'):human;
 useEffect(()=>{if(gameId&&remoteReady)setFlipped(myColor==='black');},[gameId,remoteReady,myColor]);
 useEffect(()=>{if(!hydrated||mode!=='cpu'||state.position.turn===human||gameEnded||cursor!==null)return;const id=crypto.randomUUID();const current=new Worker(new URL('../../workers/cpu.worker.ts',import.meta.url));worker.current=current;setThinking(true);current.onmessage=(event:MessageEvent<{id:string;move?:Move;error?:string}>)=>{if(event.data.id!==id)return;setThinking(false);if(event.data.error){setError(event.data.error);return;}if(event.data.move){try{const next=play(boardState.current,event.data.move);boardState.current=next;setState(next);setSelected(null);}catch{setError('The computer returned an invalid move. Start a new game to retry.');}}};current.onerror=()=>{setThinking(false);setError('The computer could not start. Try a same-device game or reload.');};current.postMessage({id,position:state.position,level});return()=>{current.terminate();worker.current=null;setThinking(false);};},[state,mode,human,level,gameEnded,cursor,hydrated]);
 const shown=cursor===null?state:replay(state.moves.slice(0,cursor));
 const analysisPly=cursor??state.moves.length;
 const displayedPosition=analysisMoves&&suggestion&&analysisPly>0?afterLegalMove(replay(state.moves.slice(0,analysisPly-1)).position,suggestion):shown.position;

 function beginAnalysis(){setMenuOpen(false);setResultDismissed(true);setCursor(0);setSuggestion(null);setAnalysisMoves([...state.moves]);}
 function closeAnalysis(){setAnalysisMoves(null);setSuggestion(null);setCursor(null);}
 const canMove=!gameEnded&&!busy&&cursor===null&&(mode==='local'||(mode==='cpu'&&!thinking&&state.position.turn===human)||(mode==='online'&&connected&&remote?.status==='active'&&state.position.turn===myColor));
 const targets=selected===null?[]:legalMoves(shown.position,selected).map(m=>m.to);
 async function send(action:Command['action'],move?:Move){if(!remote)return;setBusy(true);setError('');try{receive(await api<OnlineGame>(`games/${remote.id}/command`,{commandId:crypto.randomUUID(),version:remote.version,action,...(move?{move}:{})}));setSelected(null);}catch(e){setError(e instanceof Error?e.message:'Could not submit move.');await refreshRemote();}finally{setBusy(false);}}
 function choose(square:number){if(!canMove){if(cursor!==null)setNotice('Return to the latest move to continue.');return;}setError('');const piece=state.position.board[square];if(selected!==null&&targets.includes(square)){const move={from:selected,to:square};if(mode==='online')void send('move',move);else{const next=play(state,move);boardState.current=next;setState(next);setSelected(null);}return;}if(piece?.color===state.position.turn){setSelected(selected===square?null:square);}else if(selected!==null){setNotice('That move is not legal. Choose one of the highlighted intersections.');}}
 function start(nextMode:Mode='cpu',force=false){if(state.moves.length&&!gameEnded&&!force){setConfirmReset(true);return;}worker.current?.terminate();sessionId.current=crypto.randomUUID();setSavedVersion(-1);setAnalysisMoves(null);setSuggestion(null);setResultDismissed(false);const next=newGame();boardState.current=next;soundState.current={moveCount:0,ended:false};setState(next);setMode(nextMode);setCursor(null);setSelected(null);setResigned(null);setError('');setNotice('');setFlipped(human==='black');setConfirmReset(false);setMenuOpen(false);playSound('start');}
 async function challenge(){setError('');setBusy(true);try{const game=await api<OnlineGame>('challenge',{});router.push(`/game/${game.id}`);}catch(e){setError(e instanceof Error?e.message:'Could not create a game.');}finally{setBusy(false);}}
 async function cancelQueue(){try{const result=await api<{gameId:string|null}>('queue',{cancel:true});setQueued(false);if(result.gameId)router.push(`/game/${result.gameId}`);}catch(e){setError(e instanceof Error?e.message:'Could not cancel.');}}
 async function save(){if(!user)return;setBusy(true);try{await api('practice',{id:practiceSaveId(user.id,sessionId.current),moves:state.moves,label:mode==='cpu'?`CPU practice · level ${level}`:'Same-device game'});setSavedVersion(state.moves.length);setNotice('Saved to your game history.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 const userId=user?.id;
 useEffect(()=>{
   if(!hydrated||!userId||gameId||!gameEnded||!state.moves.length)return;
   let cancelled=false;
   void (async()=>{try{await api('practice',{id:practiceSaveId(userId,sessionId.current),moves:state.moves,label:mode==='cpu'?`CPU practice · level ${level}`:'Same-device game'});if(!cancelled){setSavedVersion(state.moves.length);setNotice('Saved to your game history.');}}catch(e){if(!cancelled)setError(e instanceof Error?`Game not saved: ${e.message} Open the menu to retry Save game.`:'Game not saved. Open the menu to retry Save game.');}})();
   return()=>{cancelled=true;};
 },[hydrated,userId,gameId,gameEnded,state.moves,mode,level]);
 const elapsed=remote?.status==='active'&&remote.turn_started!==null?Math.max(0,tick+serverOffset-remote.turn_started):0;
 const remaining=(color:Color)=>remote?Math.max(0,(color==='red'?remote.red_ms:remote.black_ms)-(remote.state.position.turn===color?elapsed:0)):0;
 const winner=remote?.winner||state.outcome?.winner||(resigned?opposite(resigned):null),reason=remote?.reason||state.outcome?.reason||(resigned?'resignation':null);
 const activeName=state.position.turn==='red'?'Red':'Black';
 const topColor:Color=flipped?'red':'black',bottomColor=opposite(topColor);
 function playerName(color:Color){if(remote)return(color==='red'?remote.red_name:remote.black_name)||'Waiting for a friend';if(mode==='local')return color==='red'?'Red player':'Black player';return color===human?'You':'Computer';}
 function playerBar(color:Color){return <div className={`player-bar ${state.position.turn===color&&!gameEnded?'turn':''}`}><div className={`avatar ${color}`}>{mode==='cpu'&&color!==human?<Cpu size={22}/>:<span>{color==='red'?'帥':'將'}</span>}</div><div className="player-info"><strong>{playerName(color)}</strong><span>{color==='red'?'Red side':'Black side'}{mode==='cpu'&&color!==human?` · Level ${level}`:''}{remote?' · Casual':''}</span></div>{remote?<span className={`clock ${remaining(color)<30000?'low':''}`}>{clock(remaining(color))}</span>:<span className="untimed">UNTIMED</span>}</div>;}
 const viewIndex=cursor??state.moves.length;
 return <div className={`play-page ${analysisMoves?'analyzing':''}`}>
 <div className="play-layout"><section className="game-surface" aria-label="Game">{playerBar(topColor)}<div className="board-stage"><Board position={displayedPosition} selected={selected} targets={targets} onSquare={choose} flipped={flipped} labels={labels} lastMove={analysisMoves&&suggestion?suggestion:shown.moves.at(-1)} disabled={!canMove}/>{gameEnded&&!menuOpen&&!analysisMoves&&!resultDismissed&&<div className="game-result" role="status"><span>GAME OVER</span><h2>{winner?(mode==='local'?`${winner==='red'?'Red':'Black'} wins`:winner===myColor?'You win!':'You lose'):state.outcome?.review||remote?.status==='review'?'Review required':reason==='agreement'?'Draw':'Game ended'}</h2><p>{reasonLabel[reason||'']||reason}</p>{state.moves.length>0&&<button className="button primary" onClick={beginAnalysis}>Analyze game</button>}<button className="text-link" onClick={()=>setResultDismissed(true)}>View final board</button></div>}</div>{playerBar(bottomColor)}<div className="board-toolbar"><div role="status" className={`live-status ${!gameEnded&&inCheck(shown.position)?'check-status':''} ${cursor!==null?'reviewing':''}`}><i className={thinking||busy?'pulsing':''}/>{analysisMoves?`Analysis · ${analysisPly}/${state.moves.length}${suggestion?' · suggested':''}`:cursor!==null?`Viewing move ${cursor} of ${state.moves.length}`:mode==='online'&&!connected?'Reconnecting…':gameEnded?(winner?`${winner==='red'?'Red':'Black'} wins`:'Game ended'):remote?.status==='waiting'?'Waiting for your friend':thinking?'Computer is thinking…':busy?'Submitting move…':inCheck(state.position)?`${activeName} is in check`:`${activeName} to move`}</div><div>{cursor!==null&&<button className="return-live" onClick={()=>{setCursor(null);setSelected(null);}} aria-label="Return to live position"><ChevronsRight size={15}/><span>Live</span></button>}<button className="icon-button" aria-label="Previous move" disabled={viewIndex===0} onClick={()=>{setCursor(Math.max(0,viewIndex-1));setSuggestion(null);setSelected(null);}}><ChevronLeft size={18}/></button><button className="icon-button" aria-label="Next move" disabled={cursor===null} onClick={()=>{setSuggestion(null);setCursor(viewIndex+1>=state.moves.length?null:viewIndex+1);}}><ChevronRight size={18}/></button><button className="game-menu-button" aria-label="Game menu" aria-haspopup="dialog" onClick={()=>setMenuOpen(true)}><Menu size={18}/><span>{state.moves.length} ply</span></button></div></div></section>
 <GameDialog open={menuOpen} onClose={()=>setMenuOpen(false)} title="Game menu"><aside className="side-panel"><div className="game-preferences"><button className="icon-button" onClick={toggleMuted} aria-label={muted?'Turn sounds on':'Mute game sounds'} aria-pressed={muted}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}</button><button className="icon-button" onClick={()=>setFlipped(!flipped)} aria-label="Flip board"><ArrowLeftRight size={17}/></button><button className={`notation-toggle ${labels?'selected':''}`} onClick={()=>{setLabels(!labels);localStorage.setItem('figure-labels',String(!labels));}} aria-pressed={labels} aria-label="Use English piece labels">Aa</button></div>
 {!gameId?<section className="card play-card"><div className="panel-tabs" role="tablist" aria-label="Choose game type">{([['computer','Computer',Cpu],['friend','Friend',Users],['match','Online',Globe2]] as const).map(([id,label,Icon])=><button role="tab" aria-selected={panel===id} key={id} className={panel===id?'active':''} onClick={()=>setPanel(id)}><Icon size={17}/>{label}</button>)}</div>
 {panel==='computer'?<div className="setup"><h2>Computer game</h2><label className="field-label" htmlFor="strength">Computer strength</label><select id="strength" value={level} onChange={e=>setLevel(Number(e.target.value))}><option value={1}>1 · Getting started</option><option value={2}>2 · A little challenge</option><option value={3}>3 · Think a step ahead</option></select><div className="setup-bottom"><div><span className="field-label">Play as</span><div className="side-choice"><button className={human==='red'?'selected':''} onClick={()=>{setHuman('red');setFlipped(false);}} disabled={state.moves.length>0&&!gameEnded}>Red</button><button className={human==='black'?'selected':''} onClick={()=>{setHuman('black');setFlipped(true);}} disabled={state.moves.length>0&&!gameEnded}>Black</button></div></div><div className="time-choice"><span className="field-label">Time control</span><span>∞ <small>Take your time</small></span></div></div><button className="button primary full" onClick={()=>start('cpu')}><Play size={17}/>New computer game<ArrowUpRight size={17}/></button><p className="micro">No account needed. No pressure.</p></div>:panel==='friend'?<div className="setup"><h2>Play a friend</h2><p className="muted">Share a private 10 + 5 game, or pass the board on the same device.</p>{!user?<Link className="button primary full" href="/account">Sign in to invite a friend <ArrowUpRight size={17}/></Link>:<button className="button primary full" disabled={busy||!online} onClick={challenge}>Create invitation <ArrowUpRight size={17}/></button>}<button className="button secondary full" onClick={()=>start('local')}>Play on this device <Users size={17}/></button><p className="micro">Online games are casual during the prototype.</p></div>:<div className="setup"><h2>Online game</h2><p className="muted">Join the 10 + 5 casual queue. Ten minutes to begin, five seconds added per move.</p>{queued?<><div className="queue-status"><LoaderCircle className="spin" size={22}/><strong>Finding a player…</strong><span>{queueSince?Math.max(0,Math.floor((tick-queueSince)/1000)):0}s in queue</span></div><button className="button secondary full" onClick={()=>void cancelQueue()}>Cancel search</button></>:user?<button className="button primary full" disabled={!online} onClick={()=>setQueued(true)}>Find a game <ArrowUpRight size={17}/></button>:<Link className="button primary full" href="/account">Sign in to find a game <ArrowUpRight size={17}/></Link>}<p className="micro">Ratings unlock after competition-rule verification. No bots in the human queue.</p></div>}
 {confirmReset&&<div className="inline-confirm" role="alert"><p>Start over? The current game will be replaced. Save it first if you want to keep it.</p><button className="button primary" onClick={()=>start(panel==='friend'?'local':'cpu',true)}>Start new game</button><button className="button secondary" onClick={()=>setConfirmReset(false)}>Keep playing</button></div>}</section>:<section className="card setup"><div className="card-eyebrow">PRIVATE TABLE · 10 + 5</div><h2>{remote?.status==='waiting'?'Invite your opponent.':'Across the river.'}</h2>{!user&&!loading?<><p className="muted">Sign in to join this table. Your invitation stays in the address bar.</p><Link className="button primary" href={`/account?next=/game/${gameId}`}>Sign in to join</Link></>:remote?.status==='waiting'?<><p className="muted">Share this link. Your friend plays Black. The clock starts when they join. Invitations expire after 30 minutes.</p><label htmlFor="invite-url" className="field-label">Invitation link</label><input id="invite-url" className="invite-url" readOnly value={inviteUrl} onFocus={event=>event.target.select()}/><button className="button secondary full" onClick={async()=>{try{if(navigator.share)await navigator.share({title:"Chinese Chess invitation",url:inviteUrl});else{await navigator.clipboard.writeText(inviteUrl);setCopied(true);}}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setNotice("Select and copy the invitation link above.");}}}><Share2 size={17}/>Share invitation</button><button className="button primary full" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);}catch{setNotice('Select and copy the invitation link above.');}}}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Invitation copied':'Copy invitation'}</button><button className="text-link" onClick={()=>void send('cancel')}>Cancel invitation</button></>:<p className="muted">{connected?'Your moves are saved automatically.':'Reconnecting… Your clock continues while disconnected.'} You are playing {myColor}.</p>}{user&&!remote&&error&&<button className="button secondary full" onClick={()=>location.reload()}>Retry joining</button>}{remote&&!connected&&<button className="button secondary full" onClick={()=>void refreshRemote()}>Reconnect now</button>}<p className="micro">Casual rules · Repetition may require review.</p></section>}
 {(error||notice)&&<div className={`message ${error?'error':''}`} role={error?'alert':'status'}><span>{error||notice}</span><button onClick={()=>{setError('');setNotice('');}} aria-label="Dismiss message">×</button></div>}
 {gameEnded&&<section className="card result-card" role="status"><div className="card-eyebrow">{remote?.status==='review'||state.outcome?.review?'REVIEW REQUIRED':'GAME COMPLETE'}</div><h2>{winner?`${winner==='red'?'Red':'Black'} wins.`:remote?.status==='review'||state.outcome?.review?'Position held for review.':reason==='agreement'?'A game shared.':'Table closed.'}</h2><p>{reasonLabel[reason||'']||reason}</p>{(state.outcome?.review||remote?.status==='review')&&<p className="micro">No result or rating awarded. This prototype does not adjudicate complex perpetual chases.</p>}</section>}
 {remote?.status==='finished'&&<section className="card setup"><h3>Another game?</h3>{remote.rematch_id?<Link className="button primary full" href={`/game/${remote.rematch_id}`}>Open rematch</Link>:remote.rematch_by===user?.id?<><p role="status">Rematch offered. Waiting for your opponent.</p><button className="button secondary full" disabled={busy} onClick={()=>void send('decline-rematch')}>Cancel rematch offer</button></>:remote.rematch_by?<><p role="status">Your opponent wants a rematch. You will switch sides.</p><button className="button primary full" disabled={busy} onClick={()=>void send('accept-rematch')}>Accept rematch</button><button className="button secondary full" disabled={busy} onClick={()=>void send('decline-rematch')}>Decline rematch</button></>:<button className="button primary full" disabled={busy} onClick={()=>void send('offer-rematch')}>Offer rematch</button>}</section>}
 <section className="card moves-card"><div className="card-title"><h3>Move journal</h3><span>{state.moves.length} half-moves</span></div><div className="move-list" aria-label="Move history">{!state.moves.length?<div className="empty-journal"><span>一</span><p>Every game starts with an idea.</p><small>Your moves will appear here.</small></div>:Array.from({length:Math.ceil(state.moves.length/2)},(_,i)=><div className="move-row" key={i}><span>{i+1}.</span>{[i*2,i*2+1].map(j=>state.moves[j]?<button key={j} className={viewIndex===j+1?'current':''} onClick={()=>{setCursor(j+1===state.moves.length?null:j+1);setSelected(null);}} title={describeMove(replay(state.moves.slice(0,j)).position,state.moves[j])}>{moveUci(state.moves[j])}</button>:<span key={j}/>)}</div>)}</div><div className="replay-controls"><button aria-label="First position" disabled={!state.moves.length} onClick={()=>{setCursor(0);setSelected(null);}}><ChevronsLeft size={18}/></button><button aria-label="Previous move" disabled={viewIndex===0} onClick={()=>{setCursor(Math.max(0,viewIndex-1));setSelected(null);}}><ChevronLeft size={18}/></button><button aria-label="Next move" disabled={cursor===null} onClick={()=>{setSuggestion(null);setCursor(viewIndex+1>=state.moves.length?null:viewIndex+1);}}><ChevronRight size={18}/></button><button aria-label="Latest position" disabled={cursor===null} onClick={()=>setCursor(null)}><ChevronsRight size={18}/></button></div><p className="history-shortcut">Use ← → outside the board to browse moves</p></section>
 <div className="game-actions">{mode==='online'?<><button className="button subtle" disabled={busy||remote?.status!=='active'} onClick={()=>void send('offer-draw')}>Offer draw</button><button className="button subtle" disabled={busy||remote?.status!=='active'} onClick={()=>{if(confirm('Resign this game?'))void send('resign');}}><Flag size={15}/>Resign</button></>:<><button className="button subtle" disabled={!state.moves.length||gameEnded} onClick={()=>{if(confirm('Resign this game?'))setResigned(mode==='cpu'?human:state.position.turn);}}><Flag size={15}/>Resign</button><button className="button subtle" disabled={!state.moves.length||!user||busy} onClick={()=>void save()}><Bookmark size={15}/>{savedVersion===state.moves.length?'Saved':'Save game'}</button></>}{gameEnded&&state.moves.length>0&&<button className="button secondary" onClick={beginAnalysis}>Analyze game</button>}{gameId&&gameEnded&&<Link className="button subtle" href="/"><RotateCcw size={15}/>New game</Link>}</div>
 {remote?.draw_by&&remote.draw_by!==user?.id&&remote.status==='active'&&<div className="card setup"><p>Your opponent offers a draw.</p><button className="button primary" disabled={busy} onClick={()=>void send('accept-draw')}>Accept draw</button><button className="button secondary" onClick={()=>void send('decline-draw')}>Keep playing</button></div>}
 <nav className="game-links" aria-label="Game navigation"><Link href="/learn">Learn</Link><Link href="/history">Your games</Link><Link href="/leaderboard">Ratings</Link></nav>
 </aside></GameDialog>{analysisMoves&&<GameAnalysis moves={analysisMoves} ply={analysisPly} onSelect={(ply,best)=>{setCursor(ply);setSuggestion(best??null);}} onClose={closeAnalysis}/>}</div>
 {(error||notice||(!connected&&remote)||remote?.draw_by&&remote.draw_by!==user?.id||remote?.rematch_by&&remote.rematch_by!==user?.id||queued)&&<button className="game-alert" onClick={()=>setMenuOpen(true)}>{error||notice||(!connected?'Connection lost — reconnect':queued?'Finding a player…':remote?.draw_by?'Draw offered — respond':'Rematch offered — respond')}</button>}
 {gameEnded&&resultDismissed&&!menuOpen&&state.moves.length>0&&!analysisMoves&&<button className="analysis-shortcut" onClick={beginAnalysis}>Analyze game</button>}

 </div>;
}
