'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowUpRight, LogOut } from 'lucide-react';
import { api, useApp } from '@/components/providers';
export default function Account(){const{user,online,loading,refresh}=useApp(),router=useRouter();const[signup,setSignup]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await api(signup?'register':'login',{username,password});setPassword('');await refresh();const next=new URLSearchParams(location.search).get('next');router.push(next&&/^\/game\/[a-f0-9-]+$/.test(next)?next:'/');}catch(e){setError(e instanceof Error?e.message:'Could not sign in.');}finally{setBusy(false);}}
 return <div className="content-page"><div className="account-layout"><div className="account-intro"><div className="large-seal">棋</div><p className="eyebrow">A PLACE AT THE TABLE</p><h1>Your games.<br/>Your next chapter.</h1><p>Keep the games that taught you something. Find another opponent. Come back to a position with fresh eyes.</p></div>{loading?<p className="loading">Checking your account…</p>:user?<section className="card account-form"><div className="card-eyebrow">WELCOME BACK</div><h2>{user.username}</h2><div className="stat-grid"><div className="stat"><strong>{user.rating}?</strong><span>Provisional Elo</span></div><div className="stat"><strong>{user.rated_games}</strong><span>Rated games</span></div><div className="stat"><strong>10+5</strong><span>Online pace</span></div></div><p className="micro">Rated play is locked during rules verification. Casual and CPU games do not change Elo.</p><Link href="/history" className="button primary full">View your games<ArrowUpRight size={17}/></Link><Link href="/" className="button secondary full">Back to the board</Link><button className="text-link" onClick={async()=>{await api('logout',{});await refresh();}}><LogOut size={15}/>Sign out</button></section>:<form className="card account-form" onSubmit={submit}><div className="card-eyebrow">{signup?'JOIN THE CLUB':'WELCOME BACK'}</div><h2>{signup?'Make yourself at home.':'Take your seat.'}</h2>{!online&&<div className="message">Accounts and online play are not available on this preview. You can play the computer without signing in.</div>}<label htmlFor="username">Username<input id="username" autoComplete="username" minLength={3} maxLength={20} pattern="[a-zA-Z0-9_]+" required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Your name at the table"/></label><label htmlFor="password">Password<input id="password" type="password" autoComplete={signup?'new-password':'current-password'} minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 12 characters"/></label>{error&&<div className="message error" role="alert">{error}</div>}<button className="button primary full" disabled={busy||!online}>{busy?'One moment…':signup?'Create account':'Sign in'}<ArrowUpRight size={17}/></button><button type="button" className="text-link" onClick={()=>{setSignup(!signup);setError('');}}>{signup?'Already have an account? Sign in':'New here? Create an account'}</button><p className="micro">Prototype accounts use a username and password. There is no email recovery yet—use a password manager and a password unique to this prototype.</p></form>}</div></div>;
}
